env:
  es2021: true
  node: true
  jest: true

extends:
  - eslint:recommended

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: 'off'
  indent: ['error', 2]
  linebreak-style: ['error', 'unix']
  quotes: ['error', 'single']
  semi: ['error', 'always']